name: Moodle Plugin CI

on:
  # pull_request:
  #   branches: [main]
  #   paths: ["moodle-plugin/**"]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: "postgres"
          POSTGRES_HOST_AUTH_METHOD: "trust"
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      fail-fast: false
      matrix:
        php: ["8.2"]
        moodle-branch: ["MOODLE_501_STABLE"]
        database: ["pgsql"]

    steps:
      - name: Check out filter_vidrouter
        uses: actions/checkout@v4
        with:
          path: plugin-filter

      - name: Check out local_vidrouter
        uses: actions/checkout@v4
        with:
          path: plugin-local

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pgsql, zip, gd, xmlrpc, soap, intl
          ini-values: max_input_vars=5000
          coverage: xdebug

      - name: Deploy moodle-plugin-ci
        run: |
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^4
          echo $(cd ci/bin; pwd) >> $GITHUB_PATH
          echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
          sudo locale-gen en_AU.UTF-8
          echo "MOODLE_DIR=$(pwd)/moodle" >> $GITHUB_ENV
          echo "DB=pgsql" >> $GITHUB_ENV

      - name: Install Moodle + plugins
        run: >
          moodle-plugin-ci install --db-host=127.0.0.1
          --plugin ./plugin-filter/moodle-plugin/filter/vidrouter
          --plugin ./plugin-local/moodle-plugin/local/vidrouter
        env:
          DB: ${{ matrix.database }}
          MOODLE_BRANCH: ${{ matrix.moodle-branch }}

      - name: PHPUnit
        run: >
          moodle-plugin-ci phpunit --fail-on-warning --coverage-text --coverage-clover
          ./plugin-filter/moodle-plugin/filter/vidrouter

      - uses: actions/upload-artifact@v4
        with:
          name: php-coverage
          path: coverage.xml

      - name: Comment coverage on PR
        if: github.event_name == 'pull_request'
        uses: slavcodev/coverage-monitor-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coverage_path: coverage.xml
          threshold_alert: 50
          threshold_warning: 75
